services:
  - type: web
    name: pawnee-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn PAWNEE.wsgi:application"
    runtime: python
    region: oregon
    branch: deploy
    rootDir: PAWNEE
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PAWNEE.settings
      - key: SECRET_KEY
        value: django-insecure-t-ww6q4l^f7#141d7-03i8!530qr6hkwi*b*v980%mo(uu1pw!
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: discoverpawnee.com,www.discoverpawnee.com
